
services:
  app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5050"  
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
