
services:
  app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5050"  # Expose the app service's internal port
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map NGINX to port 80 on the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX configuration
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
